name: Main Build
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: ${{matrix.os}} - ${{matrix.arch}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ linux, mswin ]
        arch: [ x86-64, i686 ]
        include:
        - os: linux
          arch: x86-64
          toolchain_file: 'x64-64-gcc.cmake'
          extra_packages: 'gcc g++ mesa-utils mesa-common-dev xorg-dev libxrandr-dev'
          
        - os: linux
          arch: i686
          toolchain_file: 'i686-gcc.cmake'
          extra_packages: 'gcc-multilib g++-multilib mesa-utils mesa-common-dev:i386 xorg-dev libxrandr-dev'
          
        - os: mswin
          arch: x86-64
          toolchain_file: 'x86-64-w64-mingw32.cmake'
          extra_packages: 'gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64'
          
        - os: mswin
          arch: i686
          toolchain_file: 'i686-w64-mingw32.cmake'
          extra_packages: 'gcc-mingw-w64-i686 g++-mingw-w64-i686'
    steps:
      - uses: actions/checkout@v3
      - name: Install things
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y cmake ${{ matrix.extra_packages }}
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/${{ matrix.toolchain_file }}
      - name: Compile and link
        run: |
          cd build
          cmake --build . -j6
